name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install --force

      - name: Build production bundle
        run: npm run build  # Replace this with your build command

      - name: Copy build to Firebase folder
        run: cp -r build/ firebase/  # Copy build folder contents to Firebase folder

      - name: Authenticate Firebase
        run: |
          npm install -g firebase-tools
          firebase login:ci --no-localhost --token "$FIREBASE_TOKEN"

      - name: Deploy to Firebase
        run: firebase deploy --token "$FIREBASE_TOKEN" --only hosting
